source "https://rubygems.org"

ruby "3.2.2"

gem "rails", "~> 7.1.5", ">= 7.1.5.2"
gem "sqlite3", ">= 1.4"
gem "puma"

# For password encryption
gem "bcrypt", "~> 3.1"

# For JSON Web Token authentication
gem "jwt", "~> 3.1"

# For CORS (Cross-Origin access from React frontend)
gem "rack-cors", "~> 3.0"

# For faster boot
gem "bootsnap", ">= 1.4.4", require: false
gem 'pg', group: :production


group :development, :test do
  gem "rspec-rails"
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
  gem "factory_bot_rails"
  gem "faker"
end

group :development do
  gem "listen", "~> 3.3"
  gem "rack-mini-profiler", "~> 2.0"
  gem "spring"
  gem "web-console", ">= 4.1.0"
end

gem "tzinfo-data"
